#!/bin/bash
set -eux
PGDATA=${PGDATA:-$CONDA_DIR/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

#Copy the initialisation files into the final container
mv init_db $CONDA_DIR/
chmod +x $CONDA_DIR/init_db/postgres/init_db.sh
$CONDA_DIR/init_db/postgres/init_db.sh

jupyter nbextension install --py luxwidget --user
jupyter nbextension enable --py luxwidget

python scripts/upload_data.py
